//! Path classification: the safety-critical core.
//!
//! Correctness here matters more than anywhere else in the crate, because the
//! catastrophic tier is the one protection that cannot be talked around. It is
//! therefore written to be **absolute and simple**: a small set of paths that
//! may never be recursively destroyed, compared after normalization, with no
//! dependence on correctly understanding the surrounding command.

use super::{RiskContext, RiskFinding, RiskLevel};
use std::path::{Component, Path, PathBuf};

/// Credential stores. Protected *recursively*: destroying a single private key
/// inside `~/.ssh` is as damaging as destroying the directory, so containment
/// matters here and exact-match alone would leave an obvious hole.
const PROTECTED_CREDENTIAL_SUBPATHS: &[&str] = &[".ssh", ".gnupg", ".aws", ".kube", ".docker"];

/// Directories whose *wholesale* destruction is unacceptable, but whose
/// individual files are legitimately edited and removed all the time. Matched
/// exactly, so `~/.config` is protected while `~/.config/app/stale.toml` is not.
const PROTECTED_HOME_SUBPATHS: &[&str] = &[
    ".config",
    ".jcode",
    ".claude",
    ".local",
    ".local/share",
    "Documents",
    "Desktop",
];

/// Secret stores held as a *single file*, or as a directory whose every file is
/// a credential. Losing one is not losing a file: the credentials it held
/// cannot be regenerated by re-running anything, and replacing them means
/// re-issuing every key. `PROTECTED_CREDENTIAL_SUBPATHS` covers the classic
/// `~/.ssh` shape; these are the stores that do not live there.
///
/// Matched as prefixes, so a single keyring file inside the directory is
/// protected along with the directory itself.
const PROTECTED_SECRET_SUBPATHS: &[&str] = &[
    ".netrc",
    ".npmrc",
    ".pypirc",
    ".pgpass",
    ".password-store",
    ".local/share/keyrings",
    ".config/gh",
    ".config/gcloud",
    ".config/jcode/secrets.toml",
    ".jcode/auth.json",
];

/// Shell startup files. Destroying one does not lose a file, it changes how
/// every future shell behaves, and it can strand the user in an environment
/// their tooling assumes exists. Recovery is manual and the loss is silent
/// until the next shell starts.
///
/// This list is deliberately short and matched exactly. Its job is to catch the
/// handful of files whose loss is a configuration incident, not to escalate
/// every dotfile: a gate that interrupts routine work is one users learn to
/// click through.
const PROTECTED_SHELL_INIT_FILES: &[&str] = &[
    ".bashrc",
    ".bash_profile",
    ".bash_aliases",
    ".bash_logout",
    ".zshrc",
    ".zprofile",
    ".zshenv",
    ".zlogin",
    ".profile",
    ".inputrc",
];

/// Absolute system paths that must never be recursively destroyed.
const PROTECTED_SYSTEM_PATHS: &[&str] = &[
    "/",
    "/bin",
    "/boot",
    "/dev",
    "/etc",
    "/lib",
    "/lib64",
    "/opt",
    "/proc",
    "/root",
    "/sbin",
    "/srv",
    "/sys",
    "/usr",
    "/var",
    "/Applications",
    "/System",
    "/Library",
    "/Users",
    "/home",
];

/// System paths where the *contents* are as critical as the directory itself,
/// so deleting a single file inside them is also unacceptable.
const SYSTEM_PATHS_PROTECTED_RECURSIVELY: &[&str] = &[
    "/bin", "/boot", "/dev", "/etc", "/lib", "/lib64", "/proc", "/sbin", "/sys", "/usr",
    "/var/lib", "/System", "/Library",
];

/// The set of paths this policy protects, exposed for testing and docs.
pub struct ProtectedPaths;

impl ProtectedPaths {
    pub fn home_subpaths() -> &'static [&'static str] {
        PROTECTED_HOME_SUBPATHS
    }
    pub fn credential_subpaths() -> &'static [&'static str] {
        PROTECTED_CREDENTIAL_SUBPATHS
    }
    pub fn system_paths() -> &'static [&'static str] {
        PROTECTED_SYSTEM_PATHS
    }
    pub fn recursive_system_paths() -> &'static [&'static str] {
        SYSTEM_PATHS_PROTECTED_RECURSIVELY
    }
}

/// Resolve `~`, `$HOME`, and relative paths into something comparable.
///
/// This is lexical only: it never touches the filesystem, so it is safe to call
/// on paths that do not exist and cannot be slowed down by a hostile argument.
pub fn expand(raw: &str, ctx: &RiskContext) -> PathBuf {
    let text = expand_known_prefix(raw, ctx);
    // Never normalize unresolved substitutions away (e.g. `$UNKNOWN/..`).
    if text.contains(['$', '`']) {
        return PathBuf::from(text);
    }

    let path = PathBuf::from(&text);
    if path.is_absolute() {
        return normalize(&path);
    }
    match &ctx.working_dir {
        Some(cwd) => normalize(&cwd.join(path)),
        None => path,
    }
}

/// Expand only complete, known leading variables. Prefix lookalikes such as
/// `$HOME_BACKUP` and shell parameter operators remain unresolved.
fn expand_known_prefix(raw: &str, ctx: &RiskContext) -> String {
    for (name, value) in [
        ("HOME", &ctx.home_dir),
        ("JCODE_SCRATCH_DIR", &ctx.scratch_dir),
    ] {
        let Some(value) = value else { continue };
        for prefix in [format!("${name}"), format!("${{{name}}}")] {
            if let Some(rest) = raw.strip_prefix(&prefix)
                && (rest.is_empty() || rest.starts_with('/'))
            {
                return format!("{}{rest}", value.display());
            }
        }
    }
    if let Some(home) = &ctx.home_dir {
        if raw == "~" {
            return home.display().to_string();
        }
        if let Some(rest) = raw.strip_prefix("~/") {
            return format!("{}/{rest}", home.display());
        }
    }
    raw.to_string()
}

/// Lexically remove `.` and `..` so `/home/u/../..` is seen as `/`.
///
/// Without this, `rm -rf ~/../..` would walk straight past the protected-path
/// check. Note this is intentionally *not* symlink-aware; see the crate docs on
/// defense in depth.
pub(crate) fn normalize(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            Component::ParentDir => {
                out.pop();
            }
            Component::CurDir => {}
            other => out.push(other.as_os_str()),
        }
    }
    if out.as_os_str().is_empty() {
        return PathBuf::from("/");
    }
    out
}

/// Whether a destination is expressed relative to the workspace rather than to
/// the filesystem, so it names an ordinary project file.
///
/// `src/new.rs` is workspace-relative; `/home/u/.jcode/config.toml` is not. A
/// relocation whose destination stays inside the workspace is housekeeping and
/// must not interrupt, which is why this is checked before the protected-directory
/// clause rather than after it.
pub(crate) fn is_workspace_relative(raw: &str, ctx: &RiskContext) -> bool {
    let Some(cwd) = ctx.working_dir.as_ref().map(|cwd| normalize(cwd)) else {
        return false;
    };
    let expanded = expand(raw, ctx);
    expanded.starts_with(&cwd) && !has_unresolved_substitution(raw, ctx)
}

/// Whether a relocation destination already holds something, on this machine.
///
/// This is the one place the classifier consults the filesystem, and it only
/// escalates on a *confirmed* file: a path that does not exist cannot be
/// destroyed by being overwritten, so `mv src/old.rs src/new.rs` stays routine
/// while overwriting a real file earns a reflection turn.
///
/// The answer is only meaningful for paths this machine can see. A destination
/// under a working directory that is not this process's own is treated as
/// existing when it is a real local directory and as unknown otherwise, because
/// a remote workspace's filesystem cannot be probed from here.
pub(crate) fn destination_exists(destination: &Path, ctx: &RiskContext) -> bool {
    // A remote workspace's filesystem cannot be probed from here, and a
    // fixture's synthetic paths are not real. Only trust `exists` for a path
    // whose parent this process can actually see; otherwise report unknown,
    // which the caller treats as non-escalating because the destination is
    // already known not to be a protected path.
    let _ = ctx;
    destination.exists()
}

/// Whether a raw operand still carries a substitution after known-variable
/// expansion, meaning its concrete path is not knowable statically.
pub(crate) fn has_unresolved_substitution(raw: &str, ctx: &RiskContext) -> bool {
    expand_known_prefix(raw, ctx).contains(['$', '`'])
}

/// Whether destroying this path is categorically unacceptable.
///
/// Exposed separately because this is the single most important predicate in
/// the crate and deserves to be testable in isolation.
pub fn is_catastrophic_target(path: &Path, ctx: &RiskContext) -> bool {
    let path = normalize(path);

    // Exact system roots, plus anything inside the ones whose contents are as
    // unrecoverable as the directory itself (`/etc/passwd`). `/home` and
    // `/Users` are deliberately not recursive: a user's own project lives
    // under them, and the home directory itself is handled below.
    if PROTECTED_SYSTEM_PATHS.iter().any(|p| path == Path::new(p)) {
        return true;
    }
    if SYSTEM_PATHS_PROTECTED_RECURSIVELY
        .iter()
        .any(|p| path.starts_with(p))
    {
        return true;
    }

    let Some(home) = &ctx.home_dir else {
        return false;
    };
    let home = normalize(home);

    // The home directory itself.
    if path == home {
        return true;
    }
    // Credential stores, including anything inside them.
    if PROTECTED_CREDENTIAL_SUBPATHS
        .iter()
        .any(|sub| path.starts_with(home.join(sub)))
    {
        return true;
    }
    // Secret stores that do not live under a `~/.ssh`-shaped directory.
    if PROTECTED_SECRET_SUBPATHS
        .iter()
        .any(|sub| path.starts_with(home.join(sub)))
    {
        return true;
    }
    // Config and document roots, but not their individual files.
    PROTECTED_HOME_SUBPATHS
        .iter()
        .any(|sub| path == home.join(sub))
}

/// Whether a path is a shell startup file, whose destruction reconfigures every
/// future shell rather than losing recoverable content.
pub fn is_shell_init_file(path: &Path, ctx: &RiskContext) -> bool {
    let path = normalize(path);
    let Some(home) = &ctx.home_dir else {
        return false;
    };
    let home = normalize(home);
    PROTECTED_SHELL_INIT_FILES
        .iter()
        .any(|file| path == home.join(file))
}

/// Classify one resolved target, returning a finding when it is notable.
pub fn classify_target(
    expanded: &Path,
    raw: &str,
    recursive: bool,
    ctx: &RiskContext,
) -> Option<RiskFinding> {
    // Glob and variable expansion we did not perform: we cannot know the
    // footprint, so escalate rather than guess.
    if (raw.contains('*') || raw.contains('?'))
        && !expand_known_prefix(raw, ctx).contains(['$', '`'])
    {
        // A bare `/*` or `~/*` is catastrophic in effect even though no single
        // resolved path is protected.
        if let Some(parent_of_glob) = expanded.parent()
            && is_catastrophic_target(parent_of_glob, ctx)
            && expanded.file_name().is_some_and(|n| n == "*")
        {
            return Some(RiskFinding {
                level: RiskLevel::Catastrophic,
                reason: "would destroy the entire contents of a protected directory".to_string(),
                target: Some(raw.to_string()),
            });
        }
        // A glob in a filename cannot escape its concrete parent directory.
        // Keep wildcard directory components conservative because their parent
        // is not the actual expansion boundary (`/home/u/*/node_modules`).
        if let Some(parent) = expanded.parent()
            && !parent.to_string_lossy().contains(['*', '?'])
        {
            let inside_cwd = ctx
                .working_dir
                .as_ref()
                .is_some_and(|cwd| parent.starts_with(normalize(cwd)));
            if inside_cwd || is_temp_path(parent) {
                return Some(RiskFinding {
                    level: RiskLevel::Low,
                    reason: "glob is bounded to the working or temporary directory".to_string(),
                    target: Some(raw.to_string()),
                });
            }
        }
        return Some(RiskFinding {
            level: RiskLevel::Confirm,
            reason: "target contains a glob, so the exact set of affected files \
                     is not known before execution"
                .to_string(),
            target: Some(raw.to_string()),
        });
    }

    // Check the resolved path first: `$HOME` expands to a protected path and
    // must be denied outright, not merely queried. Only genuinely unresolvable
    // substitutions fall through to the Confirm tier below.
    if is_catastrophic_target(expanded, ctx) {
        return Some(RiskFinding {
            level: RiskLevel::Catastrophic,
            reason: "targets a protected system or home path that must never be \
                     destroyed"
                .to_string(),
            target: Some(expanded.display().to_string()),
        });
    }

    if is_shell_init_file(expanded, ctx) {
        return Some(RiskFinding {
            level: RiskLevel::Confirm,
            reason: "destroys a shell startup file, which reconfigures every \
                     future shell rather than losing recoverable content"
                .to_string(),
            target: Some(expanded.display().to_string()),
        });
    }

    if expand_known_prefix(raw, ctx).contains(['$', '`']) {
        return Some(RiskFinding {
            level: RiskLevel::Confirm,
            reason: "target is computed at runtime (variable or command \
                     substitution), so its value cannot be checked in advance"
                .to_string(),
            target: Some(raw.to_string()),
        });
    }

    // Raw device nodes are never a safe write target.
    if expanded.starts_with("/dev")
        && !expanded.starts_with("/dev/null")
        && !expanded.starts_with("/dev/stdout")
        && !expanded.starts_with("/dev/stderr")
    {
        return Some(RiskFinding {
            level: RiskLevel::Catastrophic,
            reason: "writes directly to a device node, which can destroy a \
                     filesystem or disk"
                .to_string(),
            target: Some(expanded.display().to_string()),
        });
    }

    let inside_cwd = ctx
        .working_dir
        .as_ref()
        .is_some_and(|cwd| expanded.starts_with(normalize(cwd)));

    if inside_cwd {
        // The routine case: an agent tidying up its own workspace.
        return recursive.then(|| RiskFinding {
            level: RiskLevel::Low,
            reason: "recursive delete inside the working directory".to_string(),
            target: Some(expanded.display().to_string()),
        });
    }

    if is_temp_path(expanded) {
        return None;
    }

    // A concrete path being outside the workspace is not, by itself, a reason
    // to interrupt the agent. Protected home/system paths and unknown targets
    // have already returned above. Keep this as Low so the operation remains
    // visible in risk logs without requiring a justification retry.
    Some(RiskFinding {
        level: RiskLevel::Low,
        reason: "destructive operation targets a concrete path outside the working directory"
            .to_string(),
        target: Some(expanded.display().to_string()),
    })
}

/// Target names that announce themselves as disposable, so overwriting them is
/// ordinary housekeeping rather than data loss.
///
/// Matching is deliberately narrow and positional: a backup suffix, a scratch
/// or temp prefix, or an artifact extension. A relocation whose destination
/// carries none of these asks for a justification, because the classifier
/// cannot see whether a file is already there.
pub(crate) fn is_disposable_name(raw: &str) -> bool {
    let name = raw.rsplit('/').next().unwrap_or(raw);
    if name.is_empty() {
        return false;
    }
    let suffixes = [".bak", ".tmp", ".temp", ".orig", ".log", ".log~", "~"];
    if suffixes.iter().any(|suffix| name.ends_with(suffix)) {
        return true;
    }
    let prefixes = ["tmp", "temp", "jcode-tmp"];
    if prefixes.iter().any(|prefix| {
        name.starts_with(prefix)
            && name[prefix.len()..]
                .chars()
                .next()
                .is_none_or(|c| c == '-' || c == '_' || c == '.')
    }) {
        return true;
    }
    // A destination written into the scratch directory is scratch by
    // construction, which `is_temp_path` also covers once expanded.
    raw.contains("$JCODE_SCRATCH_DIR") || raw.contains("${JCODE_SCRATCH_DIR}")
}

/// Temp directories are conventionally disposable, so deleting inside them is
/// not worth a reflection turn.
pub(crate) fn is_temp_path(path: &Path) -> bool {
    ["/tmp", "/var/tmp", "/private/tmp"]
        .iter()
        .any(|prefix| path.starts_with(prefix))
}

#[cfg(test)]
#[path = "paths_tests.rs"]
mod paths_tests;
